@echo off
echo "PRED DA JA STARTUVATE SKRIPTATA TREBA VO NEA DA GI STAVITE"
echo "VASHETO KORISNICHKO IME I LOZINKA ZA TUNELOT."
echo "PO STARTUVANJETO, BAZATA KJE BIDE DOSTAPNA NA PORTA LOCALHOST:9999"
echo "AKO SAKATE DA SLUSHA NA DRUGA PORTA, SMENETE JA SKRIPTATA SOODVETNO"
echo "AKO SAKATE DA STOPIRATE (CTRL+C)"
pause

plink -v -ssh -2 -C -N -L 5444:localhost:5432 -pw 165eed37 t_autopartzmk@194.149.135.130

echo "VRSKATA TREBA DA STOI OTVORENA SE DODEKA IMATE PRISTAP DO SERVEROT"
echo "OVAA PORAKA KAZHUVA DEKA TUNELOT VEKJE SE ZATVORIL"
echo "AKO TOA SE SLUCHILO SAMO OD SEBE, IMATE PROBLEM SO VOSPOSTAVUVANJE"
echo "NA VRSKATA DO SERVEROT (BLOKADA) ILI VI SE POGRESHNI PARAMETRITE"
pause
